# -*- mode: python ; coding: utf-8 -*-
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 1oT OÜ. Authored by Hampus Hellsberg.

#
# Flavor-aware PyInstaller spec for YggdraSIM.
#
# The spec produces one of two bundles controlled by the ``YGGDRASIM_FLAVOR``
# environment variable at build time:
#
#   * ``clean`` (default) — Windows / macOS / Linux / Raspberry Pi target.
#     The Linux HIL supervisor/runtime modules are excluded so the bundle has
#     no residual ``pyudev`` or ``osmo-remsim`` coupling. The small APDU relay
#     helpers used by ``Tools/CardBridge`` remain available.
#   * ``full`` — Linux-only superset that ships the HIL bridge so the bundled
#     launcher can drive a SIMtrace2 through ``osmo-remsim-client-st2``.
#
# The spec generates a PyInstaller runtime hook below ``build/`` so the
# frozen binary reports its flavor/version without writing a stale build
# stamp into the source package.

import os
from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files, collect_submodules
from scripts.release.prepare_bundle_data import (
    BundleDataError,
    assert_no_ignored_python_sources,
    prepare_bundle_data,
)


# ``SPECPATH`` is the directory containing this spec file, which is the
# repository root. Do not add a ``.parent`` here — that would walk one
# level above the checkout and break resource staging plus every source
# lookup below.
ROOT = Path(SPECPATH).resolve()
KNOWN_FLAVORS = ("clean", "full")


def _resolve_flavor() -> str:
    raw = str(os.environ.get("YGGDRASIM_FLAVOR", "clean") or "clean").strip().lower()
    if raw not in KNOWN_FLAVORS:
        raise SystemExit(
            f"[yggdrasim spec] Unknown YGGDRASIM_FLAVOR={raw!r}; "
            f"expected one of {KNOWN_FLAVORS!r}."
        )
    return raw


FLAVOR = _resolve_flavor()
INCLUDE_HIL = FLAVOR == "full"


def _read_pyproject_version(repo_root: Path) -> str:
    # Simple ad-hoc reader to avoid a hard dependency on ``tomllib`` in
    # the Python environment running PyInstaller. The ``[project]
    # version = "..."`` line is always present in this repository's
    # pyproject.toml, so a regex is sufficient.
    import re

    pyproject_path = repo_root / "pyproject.toml"
    try:
        text = pyproject_path.read_text(encoding="utf-8")
    except OSError as error:
        raise SystemExit(
            f"[yggdrasim spec] unable to read project version: {error}"
        ) from error
    match = re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
    if match is None:
        raise SystemExit(
            f"[yggdrasim spec] no [project] version found in {pyproject_path}"
        )
    return match.group(1).strip()


def _write_build_metadata_hook(
    path: Path,
    flavor_value: str,
    version_value: str,
) -> None:
    payload = (
        '"""Runtime build metadata generated by yggdrasim_main.spec."""\n'
        "import sys\n"
        "import types\n\n"
        "_stamp = types.ModuleType('yggdrasim_common._build_flavor')\n"
        f"_stamp.BUILD_FLAVOR = {flavor_value!r}\n"
        f"_stamp.BUILD_VERSION = {version_value!r}\n"
        "sys.modules['yggdrasim_common._build_flavor'] = _stamp\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(payload, encoding="utf-8")


BUILD_VERSION = _read_pyproject_version(ROOT)


print(f"[yggdrasim spec] Building bundle for flavor={FLAVOR!r} (HIL={'yes' if INCLUDE_HIL else 'no'}).")


# Never pass a source directory to PyInstaller's ``datas`` argument.  A
# directory entry is walked recursively and can capture ignored operator
# workspaces, local credentials, traces, and developer-only extensions.
# ``prepare_bundle_data`` copies the exact reviewed files from
# ``scripts/release/bundle-data.json`` into a clean build directory, rejects
# symlinks/path escapes, and emits a SHA-256 inventory inside the bundle.
try:
    datas, BUNDLE_DATA_MANIFEST = prepare_bundle_data(ROOT, FLAVOR)
except BundleDataError as error:
    raise SystemExit(f"[yggdrasim spec] unsafe bundle data: {error}") from error
BUILD_METADATA_HOOK = (
    BUNDLE_DATA_MANIFEST.parent / "runtime_build_metadata.py"
)
_write_build_metadata_hook(BUILD_METADATA_HOOK, FLAVOR, BUILD_VERSION)

try:
    pysim_datas = collect_data_files("pySim", includes=["esim/asn1/**/*"])
    local_pysim_root = ROOT / "pysim"
    for source_text, destination in pysim_datas:
        source = Path(source_text)
        resolved = source.resolve(strict=True)
        if source.is_symlink() or local_pysim_root in resolved.parents:
            raise RuntimeError(
                "refusing a local/symlinked pysim checkout; install the locked "
                "pySim dependency into the build environment"
            )
        if destination.replace("\\", "/").startswith("pySim/") is False:
            raise RuntimeError(f"unexpected pySim data destination: {destination!r}")
    datas.extend(pysim_datas)
except Exception as error:
    raise SystemExit(
        f"[yggdrasim spec] pySim ASN.1 resources could not be collected safely: {error}"
    ) from error


# Third-party dependencies that are imported lazily (inside functions
# or via pySim, which ships as a data tree rather than a walked Python
# package) must be declared here or PyInstaller's graph analysis will
# not detect them. A missing entry manifests as a ``--doctor`` WARN for
# the named module and as a hard ``ImportError`` the first time the
# feature that needs it is exercised.
THIRD_PARTY_HIDDEN = [
    "Cryptodome",
    "Crypto",
    "asn1tools",
    "asn1crypto",
    "construct",
    "bidict",
    "pytlv",
    "osmocom",
    # Optional SAIP workbook extensions are excluded from public bundles, but
    # their reviewed parser/export dependencies are bundled so an
    # operator-supplied extension works consistently in frozen builds.
    "openpyxl",
    "defusedxml",
]
GUI_THIRD_PARTY_HIDDEN = [
    "fastapi",
    "fastapi.middleware.cors",
    "fastapi.responses",
    "fastapi.staticfiles",
    "uvicorn",
    "webview",
    "websockets",
]

hiddenimports = list(THIRD_PARTY_HIDDEN) + list(GUI_THIRD_PARTY_HIDDEN)
gui_hiddenimports = list(THIRD_PARTY_HIDDEN) + list(GUI_THIRD_PARTY_HIDDEN)
package_candidates = [
    "main",
    "SCP03",
    "SCP80",
    "SCP11",
    "SIMCARD",
    "yggdrasim_common",
]
published_tool_packages = [
    "Tools.ApduFuzz",
    "Tools.Asn1TlvDecode",
    "Tools.CardBridge",
    "Tools.EumDiag",
    "Tools.ProfilePackage",
    "Tools.SuciTool",
    "Tools.YggdraCore",
]
if INCLUDE_HIL:
    published_tool_packages.append("Tools.HilBridge")
else:
    clean_tool_helpers = [
        "Tools.HilBridge",
        "Tools.HilBridge.apdu_relay",
        "Tools.HilBridge.pcsc",
    ]
    hiddenimports.extend(clean_tool_helpers)
    gui_hiddenimports.extend(clean_tool_helpers)

package_candidates.extend(published_tool_packages)
try:
    assert_no_ignored_python_sources(ROOT, package_candidates)
except BundleDataError as error:
    raise SystemExit(
        f"[yggdrasim spec] unsafe Python source boundary: {error}"
    ) from error

for package_name in package_candidates:
    hiddenimports.extend(collect_submodules(package_name))
    gui_hiddenimports.extend(collect_submodules(package_name))


excludes = ["tests"]
if INCLUDE_HIL is False:
    # Keep the bundle lean by cutting the HIL supervisor stack and the
    # optional ``pyudev`` import that would otherwise trigger a Linux-only
    # dependency during analysis. ``Tools.HilBridge.apdu_relay`` and
    # ``Tools.HilBridge.pcsc`` are intentionally kept because the clean
    # Card Bridge daemon reuses those platform-neutral helpers.
    excludes.extend([
        "Tools.HilBridge.main",
        "Tools.HilBridge.supervisor",
        "Tools.HilBridge.device_reset",
        "Tools.HilBridge.router",
        "Tools.HilBridge.protocol",
        "Tools.HilBridge.proactive",
        "Tools.HilBridge.sim_modem",
        "Tools.HilBridge.live_decode_state",
        "Tools.HilBridge.live_decode_tui",
        "Tools.HilBridge.live_decode_view",
        "Tools.HilBridge.live_tshark_stream",
        "Tools.HilBridge.termshark_capture_mirror",
        "Tools.HilBridge.termshark_capture_pcap",
        "yggdrasim_common.hil_bridge_runtime",
        "pyudev",
    ])


def _analysis_for(entry_script: Path, entry_hiddenimports: list[str]) -> Analysis:
    return Analysis(
        [str(entry_script)],
        pathex=[str(ROOT)],
        binaries=[],
        datas=datas,
        hiddenimports=sorted(set(entry_hiddenimports)),
        hookspath=[],
        hooksconfig={},
        runtime_hooks=[str(BUILD_METADATA_HOOK)],
        excludes=excludes,
        noarchive=False,
    )


CLI_EXECUTABLE_NAME = f"yggdrasim-{FLAVOR}"
GUI_EXECUTABLE_NAME = f"yggdrasim-gui-{FLAVOR}"

cli_analysis = _analysis_for(ROOT / "main" / "main.py", hiddenimports)
cli_pyz = PYZ(cli_analysis.pure)

cli_exe = EXE(
    cli_pyz,
    cli_analysis.scripts,
    cli_analysis.binaries,
    cli_analysis.zipfiles,
    cli_analysis.datas,
    [],
    name=CLI_EXECUTABLE_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

gui_analysis = _analysis_for(ROOT / "main" / "gui.py", gui_hiddenimports)
gui_pyz = PYZ(gui_analysis.pure)

gui_exe = EXE(
    gui_pyz,
    gui_analysis.scripts,
    gui_analysis.binaries,
    gui_analysis.zipfiles,
    gui_analysis.datas,
    [],
    name=GUI_EXECUTABLE_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
