#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 1oT OÜ. Authored by Hampus Hellsberg.
#
# Publish the working tree — including the material git normally ignores
# — to the internal GitLab remote.
#
#   scripts/internal-sync.sh
#
# One repo, one working tree, one command. What it does underneath:
#
#   1. takes the current public branch (default: main) as the base
#   2. rebuilds the `internal` branch from it
#   3. force-adds the operator material that .gitignore hides
#   4. commits and pushes, to the GitLab remote only
#
# Why a separate branch rather than a commit-time flag on main: a commit
# is indivisible. Force-add the material into a main commit and it is in
# main's history, so the next `git push github main` publishes your keys.
# Git has no per-remote content filtering — the branch is the only seam.
#
# main is never touched, so it stays structurally incapable of carrying
# key material, and the pre-push hook refuses to send `internal` to a
# GitHub remote even if you ask it to.

set -euo pipefail

PUBLIC_BRANCH="${YGGDRASIM_PUBLIC_BRANCH:-main}"
INTERNAL_BRANCH="${YGGDRASIM_INTERNAL_BRANCH:-internal}"
GITLAB_REMOTE="${YGGDRASIM_GITLAB_REMOTE:-gitlab}"

# The untracked half of a dev checkout. These are the runtime-root
# directories every subsystem resolves through — plugins, workspace
# (certs, keysets, SGP.26 tree), and local state.
MATERIAL_PATHS=(
  "plugins"
  "Workspace"
  "state"
)

die() { printf '\033[31m[internal-sync] %s\033[0m\n' "$*" >&2; exit 1; }
info() { printf '\033[36m[internal-sync]\033[0m %s\n' "$*"; }

command -v git >/dev/null || die "git is not on PATH"
git rev-parse --git-dir >/dev/null 2>&1 || die "not inside a git repository"

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

git remote get-url "$GITLAB_REMOTE" >/dev/null 2>&1 \
  || die "no '$GITLAB_REMOTE' remote. Add it, then rerun: git remote add $GITLAB_REMOTE <url>"

REMOTE_URL="$(git remote get-url "$GITLAB_REMOTE")"
case "$REMOTE_URL" in
  *github.com*|*github.io*)
    die "remote '$GITLAB_REMOTE' points at GitHub ($REMOTE_URL). Refusing."
    ;;
esac

CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [ "$CURRENT_BRANCH" != "$PUBLIC_BRANCH" ]; then
  die "on '$CURRENT_BRANCH'; expected '$PUBLIC_BRANCH'. Set YGGDRASIM_PUBLIC_BRANCH to override."
fi

# Uncommitted tracked changes would silently ride along into the
# internal branch and then diverge from main. Make the operator resolve
# that first rather than guessing which they meant.
if ! git diff --quiet || ! git diff --cached --quiet; then
  die "you have uncommitted changes to tracked files. Commit or stash them on '$PUBLIC_BRANCH' first."
fi

BASE_SHA="$(git rev-parse HEAD)"
info "base: $PUBLIC_BRANCH @ ${BASE_SHA:0:8}"

PRESENT=()
for path in "${MATERIAL_PATHS[@]}"; do
  if [ -e "$path" ]; then
    PRESENT+=("$path")
    info "  material: $path/ ($(find "$path" -type f 2>/dev/null | wc -l | tr -d ' ') files)"
  fi
done
if [ ${#PRESENT[@]} -eq 0 ]; then
  die "none of the material paths exist locally (${MATERIAL_PATHS[*]}). Nothing to sync."
fi

# Rebuild the internal branch from the public one every time. It is a
# publication target, not a development line — never merge it back.
info "rebuilding '$INTERNAL_BRANCH' from '$PUBLIC_BRANCH'"
git checkout -q -B "$INTERNAL_BRANCH" "$BASE_SHA"

restore_public() {
  git checkout -q "$PUBLIC_BRANCH" 2>/dev/null || true
}
trap restore_public EXIT

git add -f -- "${PRESENT[@]}"

if git diff --cached --quiet; then
  info "internal branch already matches the working tree; nothing to commit"
else
  git commit -q -m "Internal snapshot of ${BASE_SHA:0:8}

Carries operator material that .gitignore keeps out of the public tree:
$(printf '  %s\n' "${PRESENT[@]}")

Generated by scripts/internal-sync.sh. Never merge this branch into
${PUBLIC_BRANCH} — it would put key material in the public history."
  info "committed"
fi

info "pushing '$INTERNAL_BRANCH' to '$GITLAB_REMOTE'"
git push --force-with-lease "$GITLAB_REMOTE" "$INTERNAL_BRANCH"

info "done. '$PUBLIC_BRANCH' is untouched and still sanitised."
