# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 1oT OÜ. Authored by Hampus Hellsberg.

"""Compatibility exports for the canonical SCP11 eIM package parser.

The live and local orchestrators intentionally share one parser so malformed
BER input cannot be classified differently depending on the selected backend.
"""

from SCP11.eim_packages import (
    ParsedEimPackage,
    TAG_ACTIVATION_CODE_0C,
    TAG_ACTIVATION_CODE_1A,
    TAG_ACTIVATION_CODE_80,
    TAG_ACTIVATION_CODE_81,
    TAG_BOUND_PROFILE_PACKAGE,
    TAG_EUICC_CONFIGURATION_A3,
    TAG_EUICC_CONFIGURATION_BF52,
    TAG_INDIRECT_PROFILE_DOWNLOAD_A1,
    TAG_INDIRECT_PROFILE_DOWNLOAD_BF50,
    TAG_PROFILE_DOWNLOAD_TRIGGER_A4,
    TAG_PROFILE_DOWNLOAD_TRIGGER_BF54,
    TAG_PROFILE_STATE_MANAGEMENT_A2,
    TAG_PROFILE_STATE_MANAGEMENT_BF51,
    TYPE_BOUND_PROFILE_PACKAGE,
    TYPE_EIM_CONFIGURATION_OBJECT,
    TYPE_EUICC_CONFIGURATION,
    TYPE_GENERIC,
    TYPE_INDIRECT_PROFILE_DOWNLOAD,
    TYPE_PROFILE_DOWNLOAD_TRIGGER,
    TYPE_PROFILE_STATE_MANAGEMENT,
    parse_eim_package,
)

__all__ = [
    "ParsedEimPackage",
    "TAG_ACTIVATION_CODE_0C",
    "TAG_ACTIVATION_CODE_1A",
    "TAG_ACTIVATION_CODE_80",
    "TAG_ACTIVATION_CODE_81",
    "TAG_BOUND_PROFILE_PACKAGE",
    "TAG_EUICC_CONFIGURATION_A3",
    "TAG_EUICC_CONFIGURATION_BF52",
    "TAG_INDIRECT_PROFILE_DOWNLOAD_A1",
    "TAG_INDIRECT_PROFILE_DOWNLOAD_BF50",
    "TAG_PROFILE_DOWNLOAD_TRIGGER_A4",
    "TAG_PROFILE_DOWNLOAD_TRIGGER_BF54",
    "TAG_PROFILE_STATE_MANAGEMENT_A2",
    "TAG_PROFILE_STATE_MANAGEMENT_BF51",
    "TYPE_BOUND_PROFILE_PACKAGE",
    "TYPE_EIM_CONFIGURATION_OBJECT",
    "TYPE_EUICC_CONFIGURATION",
    "TYPE_GENERIC",
    "TYPE_INDIRECT_PROFILE_DOWNLOAD",
    "TYPE_PROFILE_DOWNLOAD_TRIGGER",
    "TYPE_PROFILE_STATE_MANAGEMENT",
    "parse_eim_package",
]
